# Generated by Django 4.2.27 on 2025-12-13 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_organization_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('medical', 'MEDICAL'), ('safety', 'SAFETY'), ('financial', 'FINANCIAL'), ('social_support', 'SOCIAL'), ('errand', 'ERRAND'), ('education', 'EDUCATION'), ('civic', 'CIVIC'), ('environmental', 'ENVIRONMENTAL'), ('other', 'OTHER')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('funding_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('members', models.ManyToManyField(blank=True, related_name='joined_stations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='users.organization', verbose_name='Organization (Owner)')),
            ],
            options={
                'verbose_name': 'Rescue Station',
                'verbose_name_plural': 'Rescue Stations',
                'ordering': ('-date_added',),
            },
        ),
    ]
