# Generated by Django 4.2.27 on 2025-12-12 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('medical', 'MEDICAL'), ('safety', 'SAFETY'), ('financial', 'FINANCIAL'), ('social_support', 'SOCIAL'), ('errand', 'ERRAND'), ('education', 'EDUCATION'), ('civic', 'CIVIC'), ('environmental', 'ENVIRONMENTAL'), ('other', 'OTHER')], default='other', max_length=50)),
                ('urgency_level', models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH')], default='Medium', max_length=20)),
                ('ai_confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='AI Confidence')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('assigned', 'ASSIGNED'), ('resolved', 'RESOLVED'), ('cancelled', 'CANCELLED')], default='open', max_length=20)),
                ('reward_points', models.IntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ('-date_added',),
            },
        ),
    ]
