# Generated by Django 4.2.27 on 2025-12-13 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='rescue.rescuestation'),
        ),
        migrations.CreateModel(
            name='ProofOfHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('proof_media', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('proof_hash', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='issues.issue')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proof Of Help',
                'verbose_name_plural': 'Proofs Of Help',
                'ordering': ('-date_added',),
            },
        ),
    ]
