# Generated by Django 4.2.27 on 2025-12-12 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('volunteer', 'VOLUNTEER'), ('organization', 'ORGANIZATION'), ('super admin', 'SUPER_ADMIN')], default='super admin', max_length=20, verbose_name='Account Type'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('ngo', 'NGO'), ('religious org', 'RELIGIOUS_ORG'), ('charity foundation', 'CHARITY_FOUNDATION'), ('other', 'OTHER')], default='other', max_length=50, verbose_name='Organization Type')),
                ('issue_interests', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
